# Generated by Django 3.0.5 on 2020-04-26 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myszojelen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.FloatField(validators=[django.core.validators.MinValueValidator(None)])),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Product+', to='Myszojelen.Product')),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='State+', to='Myszojelen.State')),
            ],
        ),
    ]
