# Generated by Django 3.0.5 on 2020-04-26 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myszojelen', '0002_temporaryclassname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryclassname',
            name='selling_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
