# Generated by Django 3.0.5 on 2020-04-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myszojelen', '0003_auto_20200426_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemporaryClassName',
            new_name='FormInfoHandler',
        ),
    ]
